### ISSUE TITLE
[FEATURE]  Add AutoImport support for FSx Module

### ISSUE THREAD

**Issue by a13zen** [awslabs/idf-modules#133]
**Is your feature request related to a problem? Please describe.**
The current FSX module supports specifying the import/export settings for the Data Repository Associations but not setting the AutoImport config.

e.g using AutoImport from CDK docs

```
const lustreConfiguration = {
  deploymentType: fsx.LustreDeploymentType.SCRATCH_2,
  exportPath: bucket.s3UrlForObject(),
  importPath: bucket.s3UrlForObject(),
  autoImportPolicy: fsx.LustreAutoImportPolicy.NEW_CHANGED_DELETED,
};

const fs = new fsx.LustreFileSystem(this, "FsxLustreFileSystem", {
  vpc: vpc,
  vpcSubnet: vpc.privateSubnets[0],
  storageCapacityGiB: 1200,
  lustreConfiguration,
});
```

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_fsx-readme.html#lustre-data-repository-association-support

**Describe the solution you'd like**
I would like to be able to set the auto import config via module parameter

**Comment by dgraeber** [comment]
@a13zen Isn't the deployspec taking care of the auto-import?

https://github.com/awslabs/idf-modules/blob/main/modules/storage/fsx-lustre/deployspec.yaml
