### ISSUE TITLE
[FEATURE] Support specifying FSx Lustre FileSystem Storage Capacity from Parameters

### ISSUE THREAD

**Issue by a13zen** [awslabs/idf-modules#135]
**Is your feature request related to a problem? Please describe.**

Support specifying the storage capacity to use with the FSx for Lustre module via parameter.
https://github.com/awslabs/idf-modules/blob/7f0439f200410e963fc8548e50eba878af8e825c/modules/storage/fsx-lustre/stack.py#L84

Exporting the actual storage capacity as module metadata would also be required for downstream consumers (like fsx-for-lustre-on-eks-integration) modules to properly configure themselves based on the capacity. 

**Describe the solution you'd like**
- Specify storage capacity from parameter in manifest
- Export module capacity as module metadata

**Comment by dgraeber** [comment]
@a13zen My oversight...I will correct

**Comment by a13zen** [comment]
Thanks @dgraeber. It seems a little more complicated than only supporting passing in the value.
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_fsx.LustreFileSystem.html#storagecapacitygib

> The storage capacity of the file system being created.

> For Windows file systems, valid values are 32 GiB to 65,536 GiB. For SCRATCH_1 deployment types, valid values are 1,200, 2,400, 3,600, then continuing in increments of 3,600 GiB. For SCRATCH_2 and PERSISTENT_1 types, valid values are 1,200, 2,400, then continuing in increments of 2,400 GiB.

**Comment by dgraeber** [comment]
@a13zen yeah..that is denoted in the README...the end user must do the math to figure out the proper capacity increments.
