### ISSUE TITLE
[CHORE] Installation of jq on Opensearch Module

### ISSUE THREAD

**Issue by dgraeber** [awslabs/idf-modules#18]
Review if the need to install jq (in `deployspec.yaml`) of the opensearch module is necessary due to the updated version of the codebuild image.

**Comment by srinivasreddych** [comment]
The underlying codebuild docker image is an ubuntu 6.0 being sourced from [Dockerfile](https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/6.0/Dockerfile#L37,) which has `jq` already installed. All good!

**Comment by dgraeber** [comment]
so we should remove it from the opensearch module (deployspec.yaml). I see it is installed manually.
