### ISSUE TITLE
[FEATURE] Support subnet deployments to local zones in networking module

### ISSUE THREAD

**Issue by kevinsoucy** [awslabs/idf-modules#198]
**Is your feature request related to a problem? Please describe.**
When deploying a VPC, allow users to provide a list of local zones to extend the VPC into with public and/or private subnets. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by srinivasreddych** [comment]
Added the feature in this PR: https://github.com/awslabs/idf-modules/pull/188
