### ISSUE TITLE
[FEATURE] Extend EKS module to leverage self-managed node groups in local zones

### ISSUE THREAD

**Issue by kevinsoucy** [awslabs/idf-modules#199]
**Is your feature request related to a problem? Please describe.**
Due to expected regulations in China, there is a need for ADAS customers to run workloads in AWS local zones. The EKS module will need to be extended to support node groups running in local zones, which currently must be self-managed. Ideally these node groups are auto-scaling enabled using something like karpenter.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by srinivasreddych** [comment]
Looking into it
