### ISSUE TITLE
[FEATURE] Spark on EKS

### ISSUE THREAD

**Issue by kevinsoucy** [awslabs/idf-modules#200]
**Is your feature request related to a problem? Please describe.**
ADAS customers are looking for a way kubernetes-native way to run Spark Applications, using Karpenter for autoscaling. We would like a demo-able Step Function using the EKS module to spark submit an application to K8s

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by srinivasreddych** [comment]
EMR on EKS works in Localzones. Tested and linked the PR
