### ISSUE TITLE
[BUG] EMR-Serverless README not updated

### ISSUE THREAD

**Issue by kevinsoucy** [awslabs/idf-modules#215]
**Describe the bug**
[A clear and concise description of what the bug is.  Be ABSOLUTELY sure to give the path of the module (ex `modules/optionals/networking`).

Any bug that does not explicitly refer to a pertinent module will be closed without inspection.](https://github.com/awslabs/idf-modules/tree/main/modules/compute/emr-serverless)

EMR serverless app.py outputs do not match the README

**Comment by srinivasreddych** [comment]
Taking a look
