### ISSUE TITLE
[FEATURE] Mirror IDF and ADDF repos to China Gitee

### ISSUE THREAD

**Issue by kevinsoucy** [awslabs/idf-modules#232]
**Is your feature request related to a problem? Please describe.**
Our largest customers are very active in China. Unfortunately, public github is completely blocked in China. Therefore they cannot git reference modules from awslabs github even though they would like to. They are trying to figure out how to leverage Seedfarmer modules in China and considering complicated solutions like self mirroring etc. 

**Describe the solution you'd like**
I would like awslabs to maintain a mirror of idf-modules and addf-modules in China's public github (https://gitee.com/oschina). Basically when the IDF team cuts a release to github, they can additionally cut a release to Gitee or another chinese git provider, and make it accessible to seedfarmer projects in China.

**Describe alternatives you've considered**
Self-managed mirrors from public github

**Additional context**

**Comment by dgraeber** [comment]
We have not found this to be viable
