### ISSUE TITLE
[FEATURE] Flexible Storage Buckets Module Bucket Name override & Retain by Default

### ISSUE THREAD

**Issue by a13zen** [awslabs/idf-modules#6]
**Is your feature request related to a problem? Please describe.**
The current implementation for the storage/buckets module does not allow overriding bucket names, specifying which buckets are desired/not desired and sets the default retention policy to Destroy

**Describe the solution you'd like**
Allow flexible naming of buckets via overwritable parameters, configurability of which buckets to include/exclude in creation and  set the retention policy to something that is more secure by default (should be overwritable via parameters).  

**Describe alternatives you've considered**
Fork and modify the module. However, this makes this central reusable module, less reusable. 

**Additional context**

**Comment by dgraeber** [comment]
Yep...we can do this

**Comment by srinivasreddych** [comment]
Thanks for raising the issue @a13zen. I would like to better understand the need behind the ask. At this point, the buckets module creates:
1. artifacts_bucket
2. logs_bucket

Curious to know if you want the buckets module to create any other type of buckets (other than the ones listed above) and provide a switch to create them conditionally? Ideally, what all buckets you like to see the module creating?

**Comment by a13zen** [comment]
I see, I missed that the updated module doesn't create the other buckets common for Data Lake use cases. In this case, just the ability to rename and having a safer retention policy as default would be sufficient.

**Comment by srinivasreddych** [comment]
For `renaming`: We would still need to retain the ability of adding prefixes to a custom bucket name a user provides to avoid namespace collision, else we might run into stack errors. Below is a snippet on how the buckets are named today, and the prefix is a combination of `project_name` and `deployment_name` for identifying the project info and `hash` at the end is to avoid ns collisions.

```python
artifact_bucket_name = f"{project_name}-{deployment_name}-artifacts-bucket-{hash}"
```
For `retention`: We default buckets to `RETAIN` unless a parameter is specified in the manifest file as `DELETE`

**Comment by a13zen** [comment]
Global namespace collisions could be avoided by using f"{artifact_bucket_name}-{region}-{account}" which is a common method. If two buckets collide within a single account, I would expect the stack to fail. You could also default to your naming convention above, if no bucket name for that bucket is specified. Keeping the flexibility
