### ISSUE TITLE
[FEATURE] Explore Project Metadata Augmentation

### ISSUE THREAD

**Issue by dgraeber** [awslabs/idf-modules#8]
Explore extending the project metadata support (seedfarrmer.yaml) to include json (??) or other payload support for tagging / observability

```[tasklist]
### Tasks
```

**Comment by dgraeber** [comment]
- ref: configurable boto3 augmentation ?
- ref: project-level metadata for codebuild ?

**Comment by srinivasreddych** [comment]
@dgraeber Can you add more context here? Is this still valid?

**Comment by dgraeber** [comment]
@srinivasreddych I have not heard back from Nick as to whether we need to add this metadata for our projects...
