### ISSUE TITLE
Ability to define Lustre version

### ISSUE THREAD

**Issue by arpitgpt** [awslabs/idf-modules#96]
**Is your feature request related to a problem? Please describe.**

There should be an ability to define the luster version. By default, this module creates the version 2.10 for "PERSISTENT_1" deployment type. As per this [AWS Documentation](https://docs.aws.amazon.com/fsx/latest/LustreGuide/create-dra-linked-data-repo.html), version 2.10 has following limitations:
"Data repository associations, automatic export, and support for multiple data repositories aren't available on FSx for Lustre 2.10 file systems or Scratch 1 file systems."

Ability to provide the version number will allow to overcome this limitation

Module : https://github.com/awslabs/idf-modules/tree/main/modules/storage/fsx-lustre
 
**Describe the solution you'd like**
A parameter which can be passed in the yaml for defining the Lustre version number
 
**Describe alternatives you've considered**
Changing the deployment type to persistent_2

**Comment by dgraeber** [comment]
@arpitgpt can you provide a simple scenario of your use case:
Ex: the Lustre version with the filesystem type and (assumed) using S3 ....what are the exact criteria?
